# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.235:3306/dsep
    username: root
    password: Root123@
  thymeleaf:
    cache: false
#数据中台
data-mid-platform:
  # 数据中台大版本
  version: 1
  #AKSK配置
  userId: fb31622bf61e7b6367d38dc5d8cf5a8e
#  userId: 2a7dc9f4-6c8f-44da-b451-b21ad114f586
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCV81Rfw1BZYvu7JWOscOQvSivhfkBfVI5pcJCfpn0yXl1wxpwA/XFBMqppPmIdZvjTQrpBCYmjavOB5rAuVQFhsGVeKzN742truAeeum9FL/5GJrAeRO54y/mPBUTUbWFmkVLfauPVez5uUT1b6RTi2SAAn94YC27nt5IaMfjDPx1CzyK8PG2VzJwMvSYnRRXzu17eMQVLy7FaYd1afMyuimxsHign5evLbJZwkm84dDzI9asH3BofRhI7yccEig0j3BIhM9gIuS2DZjI6ic6Mui1WbIb9xn4mwW/SGGdVcdxLE0atGjuQihvFJAchrmqhFl2JGCy7+W/QC9Omq7kDAgMBAAECggEAUQfQJXuvNM6Hh+c5iJrsxB1Jvy3xbVKNLq9Uh+F5MDnMNsAs12AdzoSpj/vVG1xkxA0AB1s3FKcb9auKs07eU0L2VD/2L1GC4A/vljfbH0FDH/eSHplTYNWhA0dunXiKNNn9NZxWiCt0XjrqdHts/PUmFRBO/SFYikEp45vzeNYQz582SgX1ZUf0UaTJeT3b2FgjZMAi126vO8xRyt1Py48WTsJiEF5JibdqsiQgt3vCM0dei9AhHoqghlLdU3PnJehQpT4ve3NIXJyqm511b92sxSHND143FhpxFMwKSVamgQK0DhET3Smwu1gPiJB80zhgrsucZQlAfXxhJRATSQKBgQDmoKd3cI0Flw/etaHM1JjhSCmZbSGguMK0Yb9TUQXz8ZG/CelWMHnw5E1oedofh5eKHrFV9jzpBgo6tZVLUQind9m6XsWIrYR0vTss8gDwoIiuSkLUK8YgetZfPsp+pXYvgA6DoLYRTuhu3XOhw/83qlRBrE6TELluL0U/xOcnlwKBgQCmcoEHh9M8OWxtATkuLr6HkOdARTjjSYRGIM6uCophdduGgJGOjfnc/a64u+FxYtVbIHUN3bVkKAhQ7bNw8zO27Cb1cmPd3soWUeG6gG7HUQf6XHYENKP9GHG5e9qc0EYLL6zN21ZSpd2+4dtqAmi0BIyEUkOht4bV2opJasqHdQKBgDaNXc+E0fa2isx1TjZzO05ekWh3RfMMgRHF5UnB6pSPWZhEservQIjYl+7Uk+HNYu0K4Yuh2TqNcTH97biJDHEAioHpFPSFhsVOVYcGH27Lqkj/y9sAF7drFvYkliVq4g/OTKCaDTb+4UAIJefnwqDaK1/1cAiddh84EztISh01AoGAHj2hib+4tjFsrKVTQTvG7BR8n2W0Pz9FJASj6GUL3UcvelFzoKXU5rzEeNXR0Or2/pZ4DevhH/BSCnoVZwkYtTxUm7WLxWzL5KA91cet2NK1E1ynKH5z6PD/AIcrIeCJSVEBIWmfVmbCUgLw/WKwqTxGV2gm14PjoIkTJOGdKF0CgYA5Jpyq4KMtE8W3VO+iEQv7kKeEvn89284IwKi3KnpinlmhLrJqDDnnHJmbXVvh3i85IKBHoQzIPQbft4i1fVy+HDfIwtuFl/D0L3lD00tbE+zrtVN08NByV9/ZX7105+ZmPf96ftz5SKGrVRtsNxPwKvAVlKc4zeNCCrR1qC1rXA==
#  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClgK2ZzGtD5TS6YlpRv9F3nwVJ5QlcLb1UFMcmXjZMuvxMHmXH+izJOi03Y/6edim8VAyoGBtFlhg2lmQzED5IgHPCHJbcgH1A93i12qIdtDovnm2xPIk/CVUWHbP2AmCgBbW+DPp2MvsV0rf/xRN5rGPMQlGyUTE0qR7YBRlYHyvoeBRd5RDCm7HFnT/X8drWxRlAE9rsgzTUDW/qTajAj/gpw6LXDDaHoyCwmS2rDL2vFzdYNiVqnIqzx5+IKxdyK4EXdJuJhp4X65fm3t3UNOorws0CM+g7kNl8yn8/YdYUX+De73Eu/rHDbZwTlHCMBYldR+RGx3AtZg0Psog3AgMBAAECggEADmBwNCUCyGIXw30ZtXJBQu/oaLPhrUU35h7r8dRLST0Q/5fAZa/AxjYsiVxBWQiQtZBjjRKTA+d28P79c0Yc8vVdmOYc4Mi0mLkmnj2Aya3HRC2x/6xvi69G2eX4pQ0t0ZjNYdYEx9HD5/BnFWvMNkyYWr0EFcZhzN5IFKHUwsfGlV+218o9dNNLcSKolJ98jllgWDFq4NpPiiPClfFVU0Vmfzv5vBiJsPB+rY+gFp+WltIl2Zux9cepKPiMune3DSzoix21MOQXyl5SdgwP8iF5G9xUyPCtV/+Stlx/v/Nt8gdaUq3Sl1JGOP+TsO/IBwEexm6Ydn6yR/3c1oKVSQKBgQDbrRLwseU0V0bqrAOM8Oeyj/xD9nL/hujURG55A49IzKOufcce29dH1hp8F7OMaJLeqqhhF2BjZM5g38h8eEoSgA09ZlQycNrhN1bFHrdqMsL+qwrEuFT1nW5MpdzNQ45RT70vqNCJYEi+/IAc8iS1mYqV6q5MJCTck09tuwFvpQKBgQDA3m8RQerZoNqLRh0bTewcaZenCRDSqTnE9AUZFwraPLzbhJLX4y6OfI290k6ODB/4uGecqS4X7yikBXlTwtRnswfWmYHi4uwCvGwirCkpJ+EGG8rBOkqWUGPPnoedMEATKNrLvaVvpddhNHpCRDhU+HROQdaqNUoXMNuh95cRqwKBgQCNboatNLuO0Uo1OH4otclWq2ENGJS9c0xfrZc6jlIn2qjfZNdYRM370BrJHjFZCtLUTSePKw/Brls4/5sCmCeIda0QhNtchlBFg+13h+kqlHf6ooCSWuNIJw2mh3r7JK1yKFZzYsqwR69OVx7chAGicbJKBwgkuXiKEsWmrimkiQKBgArfv6VacRJKFmhJ0LRMZWaIsYsyYKdv8RjgpTTv7qW1TPSXeewAHAzeiuNL6y/pERhl1Tmo9DdXPZRZ1qhZUL50Apof14niP2o8E2C1EjEG1ZIRmRHh5nipGaeICZ9cLBCoegWIsL4lvIn3enkn/YEU7QHIhoDcNkwubgOowPS3AoGAFuz1NEZLCyJqCZQOvW/L79ekSzZAZOz0fEzegcrdCc7/jeJ+6jSxlIcoyFBmTNO8X0BeX2IV89N3nA6YpHdzLlKB6AWxGWp43FVKJ1nD/SGf5/Pfq2m1e2/0VlYjuHNrZAKLvDo61aZGy048KLe2I93cw8r4dEdIooCeCc3XP1M=
  #数据中台访问域名
  address: http://172.30.1.233:30003
#  address: http://172.30.1.233:30004
  oozieUrl: http://172.30.1.233:11000/oozie/v2/jobs

# hue元数据库
hue:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.235:3306/hue
    username: root
    password: Root123@

# oozie元数据库
oozie:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.235:3306/oozie
    username: root
    password: Root123@

# hive 导出数据成 csv 文件配置信息
hive-csv:
  metastoreUri: thrift://172.30.1.233:9083
  database: dsep
  readerParallelism: 1
  writerPath: hdfs://172.30.1.233:8020/tmp
