# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.1.228:3306/dsep
    username: root
    password: 1qazxsw@Yunli123
  thymeleaf:
    cache: false
#数据中台
data-mid-platform:
  #AKSK配置
  userId: 12f532be9bbda0001841abdd52753746
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFaqmJV/AbBeIvcMFgMkybOz4PEGMYPOis3Zdcpuu/moWJ7OLqAcXZ/ynOAFEMtc53W44edvnnaKC9O6JvLn9fbBBxAPiJbLtna5S4O8K40PhNtXYjTdX698Ew4RYVJLE+W3dxF0Uq64yC5oLAn8F+0an/aLDLtI3OX4GAiYU1UYQyEjAaJjiS1aOoj6fWLK90OAwEnogvaU8tLFTJRD7Qd0kzyZyKhZLxEbv6KCsn7xU1fCnEA6p2myt5FtKtPVOHWFmdZUfFMda2yoAU0PWx5SHG4rEyA7J59yoEd6SiL9xuo9uK2hwTUSFF/TM6kLcCY3FtVPDEzcR8Zu7/mLyPAgMBAAECggEAFXHNilvuJgnOD14KVxH+qjzdfsJdiznPFGoRuDzES+nkaQUAfCiIyr9u0sPOQ0K9ywWWVGM/S+jPXVtGgqRwqL/P7LoBOOWXQcpS/0HrzJUaNDNkp8wNBufnz5l+WSuqqaE+E5lv7rQpw6iVf6yuB1pf/sOvFy8QVAmZ4TU5ihYyv8at9jugk+I1rAuRnKR7D38V7OEzDtmDK4oBZ4AKXtdYr2X7iOh91X/qCHBOI66yvWzesrVXAKhwHKk4/VRRIj+wJzeME3jG2MNK525OZIe3pVkFsN8wxlgcJphiJKj7Yf1YrElY9UEH/KOgxU9oLAcvKs1gfBE6hX/udfWecQKBgQC+P7hFAys3qzVeqsALBLmEUrB/5+wsKwWtbVd5HQp8pop89LEUN7uASqnvbV1HyybSLQRKLYPu7Yfb4zRmDBKaTRxpTbEmbjIsbWanoqYGCRL1C0Wwt6Jr6qFR9SkiI4N/eT7fqFtcqUHxh5vDoT6LapzlD8xpQunCx/573jM4VQKBgQCzhrTEO4qDUpXhAXmK1FC3EF5YQH2sdNifV5hGIPBFhTYObX82EBpyWj+Q2uRLU+p4GzDDETl1G4jRYaaZxQ3K5+DLpDvyzPDuJlfARZ3Xbx/wDG0mV/JR8dXOwlpNfZOfVCfSxjTvkRbJiVBXa28aQToA61kb0DMSaC9jlGSVUwKBgQCSrFGGc0D4dDh7Oa1BUW0thQqqMcW075467JeJukgBfew7FfMHoUgfSnDlNC28UfUmCKrL/Xc/10Ts06fsHNaiu1xyGwG+nSp1cgq4pv7UnF5PKVebPJguFwA0TYxe035n4rQEfqmhMKS0b1Y5ZrDvj0xSlPGFHZ9XGhUqrk5S2QKBgBOOUfSqU71YarE2+ulvlVdLtitA4y+9DrfUz+abwfCgwTGzJc9a07avNAtwfLvj6T+qHpaxMqQaGr5MN9y6RXVb6vXj7w/U2U3n6VktfDMyjLUWdXFe1Sut/09lhna4fjM19JyWMMAD+wp7JcBQGKswfcQJ3wwTkuynYrojOQ23AoGAYi3gashXLngRFs51bILygm4Phvf91tsT3gLPL3244YJ6MVMXs2q568PALILQ76dmTlRmEQt/6qpI2VUDO4bW3fF/aRSihv80GQNaqCkuc5GDwH5wQsEbMm1ZfOCCMCJJRi9GbLWIO7iClYzCkQf8eKNgqEI4LFzlJp74qjCH6xI=
  #数据中台访问域名
  address: http://172.30.1.228:32643
  oozieUrl: http://172.30.1.233:11000/oozie/v2/jobs

# hue元数据库
hue:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.1.235:3306/hue
    username: root
    password: Root123@

# oozie元数据库
oozie:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.1.235:3306/oozie
    username: root
    password: Root123@

# hive 导出数据成 csv 文件配置信息
hive-csv:
  metastoreUri: thrift://172.30.1.233:9083
  database: bdsp
  readerParallelism: 1
  writerPath: /tmp
